pipeline:
    reader:
        - ua_edr_extractor.reader.EDRReader
        - file_path: "path-to-downloaded-data/15.1-EX_XML_EDR_UO.xml"
    preprocessor:
        - ua_edr_extractor.preprocessor.PreProcessor
        - tokenizer: "!tokenize_uk.tokenize_words"
    beneficiary_categorizer:
        - ua_edr_extractor.categorizer.HasBeneficiaryOwnershipRecord
    parser:
        - ua_edr_extractor.record_parser.EnsembleBasedParser
        -
            voters:
                -
                    - "!ua_edr_extractor.record_parser.HeuristicBasedParser"
                -
                    - "!ua_edr_extractor.record_parser.MITIEBasedParser"
                    - model: models/edr_ner_model_combined_embeddings_3class_syntetic.dat
            cutoff: 1
            merge_overlapping: True

output_file: test_data/output_simple.csv
output_format: csv
export_only_beneficial_owners: True
